// <auto-generated />
using System;
using GymQuest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymQuest.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511134102_CSAchievementTable")]
    partial class CSAchievementTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymQuest.Models.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeImageUrl = "images/badges/badge_1.png",
                            Description = "Get 10k steps",
                            ExperienceReward = 100,
                            Name = "10k steps"
                        },
                        new
                        {
                            Id = 2,
                            BadgeImageUrl = "images/badges/badge_2.png",
                            Description = "Get 20k steps",
                            ExperienceReward = 200,
                            Name = "20k steps"
                        },
                        new
                        {
                            Id = 3,
                            BadgeImageUrl = "images/badges/badge_3.png",
                            Description = "Get 30k steps",
                            ExperienceReward = 300,
                            Name = "30k steps"
                        },
                        new
                        {
                            Id = 4,
                            BadgeImageUrl = "images/badges/badge_4.png",
                            Description = "Get 40k steps",
                            ExperienceReward = 400,
                            Name = "40k steps"
                        },
                        new
                        {
                            Id = 5,
                            BadgeImageUrl = "images/badges/badge_5.png",
                            Description = "Get 50k steps",
                            ExperienceReward = 500,
                            Name = "50k steps"
                        },
                        new
                        {
                            Id = 6,
                            BadgeImageUrl = "images/badges/badge_6.png",
                            Description = "Get 60k steps",
                            ExperienceReward = 600,
                            Name = "60k steps"
                        },
                        new
                        {
                            Id = 7,
                            BadgeImageUrl = "images/badges/badge_7.png",
                            Description = "Get 70k steps",
                            ExperienceReward = 700,
                            Name = "70k steps"
                        },
                        new
                        {
                            Id = 8,
                            BadgeImageUrl = "images/badges/badge_8.png",
                            Description = "Get 80k steps",
                            ExperienceReward = 800,
                            Name = "80k steps"
                        },
                        new
                        {
                            Id = 9,
                            BadgeImageUrl = "images/badges/badge_9.png",
                            Description = "Get 90k steps",
                            ExperienceReward = 900,
                            Name = "90k steps"
                        },
                        new
                        {
                            Id = 10,
                            BadgeImageUrl = "images/badges/badge_10.png",
                            Description = "Get 100k steps",
                            ExperienceReward = 1000,
                            Name = "100k steps"
                        });
                });

            modelBuilder.Entity("GymQuest.Models.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseXP")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseXP = 35,
                            Category = "Strength",
                            MuscleGroup = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            BaseXP = 30,
                            Category = "Strength",
                            MuscleGroup = "Shoulders",
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            Id = 3,
                            BaseXP = 20,
                            Category = "Isolation",
                            MuscleGroup = "Arms",
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 4,
                            BaseXP = 40,
                            Category = "Bodyweight",
                            MuscleGroup = "Back",
                            Name = "Pull Up"
                        },
                        new
                        {
                            Id = 5,
                            BaseXP = 35,
                            Category = "Strength",
                            MuscleGroup = "Back",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 6,
                            BaseXP = 20,
                            Category = "Isolation",
                            MuscleGroup = "Arms",
                            Name = "Bicep Curl"
                        },
                        new
                        {
                            Id = 7,
                            BaseXP = 45,
                            Category = "Strength",
                            MuscleGroup = "Legs",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 8,
                            BaseXP = 35,
                            Category = "Machine",
                            MuscleGroup = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 9,
                            BaseXP = 20,
                            Category = "Isolation",
                            MuscleGroup = "Legs",
                            Name = "Leg Curl"
                        });
                });

            modelBuilder.Entity("GymQuest.Models.Entities.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chest, shoulders and triceps",
                            IsDefault = true,
                            Name = "Push"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Back and biceps",
                            IsDefault = true,
                            Name = "Pull"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Heavy leg workout",
                            IsDefault = true,
                            Name = "Legs"
                        });
                });

            modelBuilder.Entity("GymQuest.Models.Entities.RoutineExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("RoutineId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            OrderIndex = 1,
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            OrderIndex = 2,
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 3,
                            OrderIndex = 3,
                            RoutineId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 4,
                            OrderIndex = 1,
                            RoutineId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 5,
                            OrderIndex = 2,
                            RoutineId = 2
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 6,
                            OrderIndex = 3,
                            RoutineId = 2
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 7,
                            OrderIndex = 1,
                            RoutineId = 3
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 8,
                            OrderIndex = 2,
                            RoutineId = 3
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 9,
                            OrderIndex = 3,
                            RoutineId = 3
                        });
                });

            modelBuilder.Entity("GymQuest.Models.Entities.RoutineSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RoutineExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RoutineExerciseId");

                    b.ToTable("RoutineSets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RestSeconds = 90,
                            RoutineExerciseId = 1,
                            SetNumber = 1,
                            TargetReps = 8,
                            TargetWeight = 60m
                        },
                        new
                        {
                            Id = 2,
                            RestSeconds = 90,
                            RoutineExerciseId = 1,
                            SetNumber = 2,
                            TargetReps = 8,
                            TargetWeight = 65m
                        },
                        new
                        {
                            Id = 3,
                            RestSeconds = 120,
                            RoutineExerciseId = 1,
                            SetNumber = 3,
                            TargetReps = 6,
                            TargetWeight = 70m
                        },
                        new
                        {
                            Id = 4,
                            RestSeconds = 90,
                            RoutineExerciseId = 2,
                            SetNumber = 1,
                            TargetReps = 10,
                            TargetWeight = 30m
                        },
                        new
                        {
                            Id = 5,
                            RestSeconds = 90,
                            RoutineExerciseId = 2,
                            SetNumber = 2,
                            TargetReps = 10,
                            TargetWeight = 35m
                        },
                        new
                        {
                            Id = 6,
                            RestSeconds = 60,
                            RoutineExerciseId = 3,
                            SetNumber = 1,
                            TargetReps = 12,
                            TargetWeight = 20m
                        },
                        new
                        {
                            Id = 7,
                            RestSeconds = 60,
                            RoutineExerciseId = 3,
                            SetNumber = 2,
                            TargetReps = 12,
                            TargetWeight = 25m
                        });
                });

            modelBuilder.Entity("GymQuest.Models.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EarnedXP")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoutineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EarnedXP")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.RoutineExercise", b =>
                {
                    b.HasOne("GymQuest.Models.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymQuest.Models.Entities.Routine", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.RoutineSet", b =>
                {
                    b.HasOne("GymQuest.Models.Entities.RoutineExercise", "RoutineExercise")
                        .WithMany("Sets")
                        .HasForeignKey("RoutineExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoutineExercise");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.Workout", b =>
                {
                    b.HasOne("GymQuest.Models.Entities.Routine", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("GymQuest.Models.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymQuest.Models.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.WorkoutSet", b =>
                {
                    b.HasOne("GymQuest.Models.Entities.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.RoutineExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymQuest.Models.Entities.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
